#!/bin/bash

alias cue1="cd ~/Canonical/cue-01-linux-sme/"
alias cue2="cd ~/Canonical/cue-02-desktop-sme/"
alias cue3="cd ~/Canonical/cue-03-server-sme/"
alias ta="cd ~/Canonical/trueability-integration-canonical/"
