#!/bin/bash



# fd: simple, fast and user-friendly alternative to 'find', writen in rust
# https://github.com/sharkdp/fd
#
if type fdfind &> /dev/null; then
    alias fd="fdfind"
    echo "Setting 'fd' alias for fdfind. By default fd ignores hidden files."
fi

# Cli for Deepl translation: https://www.deepl.com/translator
# package deepl-cli 0.5.0, installed using pipx on Python 3.11.3
#
if type deepl &> /dev/null; then
    dpl(){
        deepl --fr en --to fr -s <<<"$1"
    }
    echo "Created 'dpl' alias for deepl cli tool"
fi
